function Hero() {
  return (
    <section className="hero">
      <p>Webbyrå & digital konsult</p>
      <h1>Vi bygger moderna hemsidor för företag</h1>
      <p>
        Vi hjälper företag att skapa professionella, responsiva och användarvänliga
        webbplatser med modern teknik.
      </p>

      <div className="hero-buttons">
        <button>Begär offert</button>
        <button>Se våra tjänster</button>
      </div>
    </section>
  )
}

export default Hero